### ISSUE TITLE
Don't wait for GUI process to terminate when launching via shim

### ISSUE THREAD

**Issue by lymanepp** [ScoopInstaller/Shim#4]
Shims always wait for the process to terminate before exiting. That is certainly the expected behavior for console applications. However, GUI applications should not wait for process termination before the shim terminates. Launch Notepad from a console and you will see that the console doesn't wait for it to terminate before returning control to the user.

I have a working patch and I will submit a pull request if this issue is accepted.

**Comment by gerardog** [comment]
Hi! I am not a maintainer of Scoop, but a involved user.
Please try kiennq shim to see if your issue is solved.

```
scoop config shim kiennq
scoop reset *
```

Also, I am not really sure this repository holds the current shim source code. But maybe that is a topic for another issue.

**Comment by gerardog** [comment]
Related lukesampson/scoop#4333 and lukesampson/scoop#3634

**Comment by pfmoore** [comment]
Why is this issue closed? The kiennq shim doesn't seem to fix this problem for me - if I install (for example) sysinternals, and then run procexp, the command line shim doesn't return until I close the GUI window.

**Comment by rashil2000** [comment]
Shims are not intended to use for GUI programs, they are for console programs (and hence they need the console). For GUI programs there are shortcuts.

**Comment by gerardog** [comment]
I can repro this issue with other GUI apps, such as WizTree.

> Shims are not intended to use for GUI programs, they are for console programs (and hence they need the console). For GUI programs there are shortcuts.

That is not true. Scoop uses shims to add applications to the path, regardless if they are GUI or CLI. There are two ways Scoop could handle this. Either a different shim is generated for GUI (with Subsystem=0x2 in the PE header) and CLI (Subsystem=3), or be a same exe but detect the Subsystem of the target app and return immediately if it is a GUI app. 

I think this is already been debated at ScoopInstaller/Scoop#1606

**Comment by pfmoore** [comment]
Thanks for the link @gerardog.

> For GUI programs there are shortcuts.

Text editors like gvim are often run from the command line to edit a file. Shortcuts don't work for that, because they don't support supplying the filename via command line arguments. Even Notepad can be used in this way.

🤷 I guess if the scoop developers aren't willing to support this use case, there's not much the users can do to change their minds.

I can think of a few hacks I can use in my own manifests to replace the shims with something GUI-friendly. Either write my own shim and use that, or just change the executable mode of the existing shim from CUI to GUI in a post-install hook. So I guess I'll do that, and live with the fact that I won't get a supported standard solution 🙁

**Comment by gerardog** [comment]
> I guess if the scoop developers aren't willing to support this use case, there's not much the users can do to change their minds

Take it easy... Governance on OSS is hard given, specially after Scoop's original author leave it to the community.

I'll do my best to suggest them what IMHO is the best approach.

**Comment by pfmoore** [comment]
Sorry - I didn't mean to come across as harsh (I'm an OSS developer myself, so I know exactly what you mean). I was intending to say that there's no point in continuing to complain about this if the decision has been made. But I put it badly. Sorry. My frustration with my particular use case was showing through.

Also, I didn't know that scoop was now community supported. If I were to try to write a PR that addressed this issue (probably by setting the shim's "GUI subsystem" flag if the target file used the GUI subsystem) would that be of interest? I can't promise anything, as I'm not an expert Powershell developer, but I'm willing to try.

**Comment by rashil2000** [comment]
> Also, I didn't know that scoop was now community supported. If I were to try to write a PR that addressed this issue (probably by setting the shim's "GUI subsystem" flag if the target file used the GUI subsystem) would that be of interest? I can't promise anything, as I'm not an expert Powershell developer, but I'm willing to try.

Yes, would be much appreciated!

There's some details regarding implementation here: https://github.com/ScoopInstaller/Scoop/issues/1606
