### ISSUE TITLE
[BUG]: Shim from releases does not pick up .shim

### ISSUE THREAD

**Issue by couleurm** [ScoopInstaller/Shim#5]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

Shim

### Expected/Current Behaviour

Using the 7.5~8kb shim.exe from the releases to use it in my own script, like I've been used to with Scoop's shims 

### Steps to Reproduce

```console
iwr https://github.com/ScoopInstaller/Shim/releases/download/v1.0.1/shim.exe -outfile ./a.exe
set-content ./a.shim -value 'path = "control.exe"'
./a.exe
```

### Possible Solution

The 125kb in the shims folder (`AA685053F4A5C0E7145F2A27514C8A56CEAE25B0824062326F04037937CAA558`) does work, where can I get it from an official source from you guys so I don't have to rehost it?

### Scoop and Buckets Version

```console
N/A
```

### Scoop Config

```console
Unrelated
```

### PowerShell Version

```console
tested 7.2.6 and 5.1
```

### Additional Softwares

Also tested on Windows Sandbox

**Comment by niheaven** [comment]
See readme, you need full path in `.shim`.

**Comment by couleurm** [comment]
That is not the problem:
```PowerShell
iwr https://github.com/ScoopInstaller/Shim/releases/download/v1.0.1/shim.exe -outfile ./a.exe
set-content ./a.shim -value "path = `"$((Get-Command control.exe).Source)`""
./a.exe
```

**Comment by gerardog** [comment]
I think the root issue is that there are [multiple outdated Scoop Shim source codes](https://github.com/ScoopInstaller/Scoop/issues/1606#issuecomment-1168042800). 

AFAIK, the Shim used by scoop is [kiennq/scoop-better-shimexe](https://github.com/kiennq/scoop-better-shimexe/releases).
That one would work.

**Comment by 29039** [comment]
I just tested this and it seems to be working as you expect now with relative paths
