### ISSUE TITLE
[FEATURE REQUEST]: Shim creation helper and context menu ?

### ISSUE THREAD

**Issue by shodanx2** [ScoopInstaller/Shim#7]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

Shim

### Expected/Current Behaviour

Creating shims is difficult as a user

Of course this software was made to be used by scoop

But there are other reasons why someone might want to use this shim program

Here is an example. I wish to create shims of these executables

![image](https://github.com/ScoopInstaller/Shim/assets/10621885/2ce8316e-0877-458e-a510-23a92d11a21a)

### Steps to Reproduce

```console
Not applicable
```

### Possible Solution

I see two ways that could be helpful.

First would be as a command line interface

Specify one or more executables and the last parameter is the shim folder.

It copies a shim executable, names it appropriately and creates a .shim file as well

Example command line

absolute path
`shim C:\Program Files (x86)\cdrtfe\tools\cdrtools\cdda2wav.exe C:\Users\user\commands`

substituted paths
`shim %ProgramFiles(x86)%\cdrtfe\tools\cdrtools\cdda2wav.exe %USERPROFILE%\commands`

multiple substituted paths
`shim %ProgramFiles(x86)%\cdrtfe\tools\cdrtools\cdda2wav.exe %ProgramFiles(x86)%\cdrtfe\tools\cdrtools\cdrecord.exe %ProgramFiles(x86)%\cdrtfe\tools\cdrtools\isoinfo.exe %ProgramFiles(x86)%\cdrtfe\tools\cdrtools\mkisofs.exe %ProgramFiles(x86)%\cdrtfe\tools\cdrtools\readcd.exe %USERPROFILE%\commands`

absolute path followed by multiple relative paths 
`shim %ProgramFiles(x86)%\cdrtfe\tools\cdrtools\cdda2wav.exe cdrecord.exe isoinfo.exe mkisofs.exe readcd.exe %USERPROFILE%\commands`

with perhaps "-s" for a command line parameter to automatically perform variable substitution in paths ?

And the other way would be as explorer context menu helper for valid executable files. As shown in my above screenshot

### Scoop and Buckets Version

```console
Not applicable
```

### Scoop Config

```console
Not applicable
```

### PowerShell Version

```console
Not applicable
```

**Comment by rashil2000** [comment]
`scoop help shim`
